version: "3.8"

services:
  db:
    image: postgres:15
    container_name: superbank_assessment
    restart: always
    environment:
      POSTGRES_USER: ermyyuhari
      POSTGRES_PASSWORD: ermy123
      POSTGRES_DB: superbank_assessment
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: golang_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "host=localhost user=ermyyuhari password=ermy123 dbname=superbank_assessment port=5432 sslmode=disable"
    ports:
      - "3000:3000"

volumes:
  db_data:
