version: "3.8"

services:
  db:
    image: postgres:15
    container_name: customer_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customerdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: golang_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "host=db user=postgres password=password dbname=customerdb port=5432 sslmode=disable"
    ports:
      - "3000:3000"

volumes:
  db_data:
